library(data.table)
library(lubridate)
data <- read.table("household_power_consumption.txt", sep =";", na.strings = "?", skip=grep("1/2/2007", readLines("household_power_consumption.txt"))-1, nrows=2880, col.names = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
data$datetime <- paste(data$Date, " ", data$Time)
data$datetime <- dmy_hms(data$datetime)
png(filename = "plot 1.png", width = 480, height = 480, units = "px")
hist(data$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)", ylab = "Frequency")
dev.off()