library(data.table)
library(lubridate)
data <- read.table("household_power_consumption.txt", sep =";", na.strings = "?", skip=grep("1/2/2007", readLines("household_power_consumption.txt"))-1, nrows=2880, col.names = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
data$datetime <- paste(data$Date, " ", data$Time)
data$datetime <- dmy_hms(data$datetime)
png(filename = "plot 3.png", width = 480, height = 480, units = "px")
plot(data$datetime, data$Global_active_power, type = "n", xlab = "", ylab = "Energy sub metering", ylim = c(0, 38))
lines(data$datetime, data$Sub_metering_1, col="black")
lines(data$datetime, data$Sub_metering_2, col="red")
lines(data$datetime, data$Sub_metering_3, col="blue")
legend("topright", lty = c(1,1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()